"""add_missing_tables

Revision ID: 01b5669c6ef9
Revises: 
Create Date: 2026-09-15 14:27:24.405422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '01b5669c6ef9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('simulations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('port_id', sa.Integer(), nullable=False),
    sa.Column('scenario_type', sa.String(length=50), nullable=False),
    sa.Column('scenario_parameters', sa.JSON(), nullable=True),
    sa.Column('baseline_metrics', sa.JSON(), nullable=True),
    sa.Column('simulated_metrics', sa.JSON(), nullable=True),
    sa.Column('impact_summary', sa.JSON(), nullable=True),
    sa.Column('mitigation_recommendations', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['port_id'], ['ports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('audit_logs', 'old_value',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('audit_logs', 'new_value',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index(op.f('idx_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('idx_berth_assignment_time'), table_name='berth_assignments')
    op.drop_constraint(op.f('unique_berth_name'), 'berths', type_='unique')
    op.drop_index(op.f('idx_congestion_prediction_time'), table_name='congestion_predictions')
    op.drop_index(op.f('idx_crane_assignment_time'), table_name='crane_assignments')
    op.drop_constraint(op.f('unique_crane_name'), 'cranes', type_='unique')
    op.add_column('operation_plan_items', sa.Column('vessel_id', sa.Integer(), nullable=False))
    op.add_column('operation_plan_items', sa.Column('planned_start', sa.DateTime(), nullable=False))
    op.add_column('operation_plan_items', sa.Column('planned_end', sa.DateTime(), nullable=False))
    op.add_column('operation_plan_items', sa.Column('shift_label', sa.String(length=50), nullable=True))
    op.alter_column('operation_plan_items', 'crane_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_constraint(op.f('fk_plan_item_schedule'), 'operation_plan_items', type_='foreignkey')
    op.drop_constraint(op.f('fk_plan_item_plan'), 'operation_plan_items', type_='foreignkey')
    op.create_foreign_key(None, 'operation_plan_items', 'vessels', ['vessel_id'], ['id'])
    op.create_foreign_key(None, 'operation_plan_items', 'operations_plans', ['plan_id'], ['id'], ondelete='CASCADE')
    op.drop_column('operation_plan_items', 'start_time')
    op.drop_column('operation_plan_items', 'end_time')
    op.drop_column('operation_plan_items', 'vessel_schedule_id')
    op.drop_column('operation_plan_items', 'shift')
    op.add_column('operations_plans', sa.Column('optimization_run_id', sa.Integer(), nullable=True))
    op.add_column('operations_plans', sa.Column('horizon_hours', sa.Integer(), nullable=False))
    op.add_column('operations_plans', sa.Column('summary_metrics', sa.JSON(), nullable=True))
    op.add_column('operations_plans', sa.Column('congestion_windows', sa.JSON(), nullable=True))
    op.add_column('operations_plans', sa.Column('recommendations', sa.JSON(), nullable=True))
    op.add_column('operations_plans', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('operations_plans', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.alter_column('operations_plans', 'status',
               existing_type=sa.VARCHAR(length=30),
               nullable=False,
               existing_server_default=sa.text("'DRAFT'::character varying"))
    op.drop_constraint(op.f('fk_plan_user'), 'operations_plans', type_='foreignkey')
    op.create_foreign_key(None, 'operations_plans', 'optimization_runs', ['optimization_run_id'], ['id'])
    op.create_foreign_key(None, 'operations_plans', 'users', ['created_by'], ['id'])
    op.drop_column('operations_plans', 'end_time')
    op.drop_column('operations_plans', 'generated_by')
    op.drop_constraint(op.f('ports_code_key'), 'ports', type_='unique')
    op.alter_column('recommendations', 'expected_impact',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index(op.f('idx_recommendations_status'), table_name='recommendations')
    op.drop_index(op.f('idx_vessel_schedule_eta'), table_name='vessel_schedules')
    op.drop_index(op.f('idx_vessel_schedule_port'), table_name='vessel_schedules')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_vessel_schedule_port'), 'vessel_schedules', ['port_id'], unique=False)
    op.create_index(op.f('idx_vessel_schedule_eta'), 'vessel_schedules', ['eta'], unique=False)
    op.create_index(op.f('idx_recommendations_status'), 'recommendations', ['status'], unique=False)
    op.alter_column('recommendations', 'expected_impact',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.create_unique_constraint(op.f('ports_code_key'), 'ports', ['code'], postgresql_nulls_not_distinct=False)
    op.add_column('operations_plans', sa.Column('generated_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('operations_plans', sa.Column('end_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'operations_plans', type_='foreignkey')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'operations_plans', type_='foreignkey')
    op.create_foreign_key(op.f('fk_plan_user'), 'operations_plans', 'users', ['generated_by'], ['id'])
    op.alter_column('operations_plans', 'status',
               existing_type=sa.VARCHAR(length=30),
               nullable=True,
               existing_server_default=sa.text("'DRAFT'::character varying"))
    op.drop_column('operations_plans', 'updated_at')
    op.drop_column('operations_plans', 'created_by')
    op.drop_column('operations_plans', 'recommendations')
    op.drop_column('operations_plans', 'congestion_windows')
    op.drop_column('operations_plans', 'summary_metrics')
    op.drop_column('operations_plans', 'horizon_hours')
    op.drop_column('operations_plans', 'optimization_run_id')
    op.add_column('operation_plan_items', sa.Column('shift', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('operation_plan_items', sa.Column('vessel_schedule_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('operation_plan_items', sa.Column('end_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('operation_plan_items', sa.Column('start_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'operation_plan_items', type_='foreignkey')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'operation_plan_items', type_='foreignkey')
    op.create_foreign_key(op.f('fk_plan_item_plan'), 'operation_plan_items', 'operations_plans', ['plan_id'], ['id'])
    op.create_foreign_key(op.f('fk_plan_item_schedule'), 'operation_plan_items', 'vessel_schedules', ['vessel_schedule_id'], ['id'])
    op.alter_column('operation_plan_items', 'crane_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_column('operation_plan_items', 'shift_label')
    op.drop_column('operation_plan_items', 'planned_end')
    op.drop_column('operation_plan_items', 'planned_start')
    op.drop_column('operation_plan_items', 'vessel_id')
    op.create_unique_constraint(op.f('unique_crane_name'), 'cranes', ['port_id', 'name'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_crane_assignment_time'), 'crane_assignments', ['start_time', 'end_time'], unique=False)
    op.create_index(op.f('idx_congestion_prediction_time'), 'congestion_predictions', ['prediction_time'], unique=False)
    op.create_unique_constraint(op.f('unique_berth_name'), 'berths', ['port_id', 'name'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_berth_assignment_time'), 'berth_assignments', ['start_time', 'end_time'], unique=False)
    op.create_index(op.f('idx_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.alter_column('audit_logs', 'new_value',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('audit_logs', 'old_value',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_table('simulations')
    # ### end Alembic commands ###
