"""initial

Revision ID: 5fab54593e28
Revises: 
Create Date: 2026-09-15 18:40:15.712295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fab54593e28'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('timezone', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('vessels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('imo_number', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('length_m', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('draft_m', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('capacity_teu', sa.Integer(), nullable=True),
    sa.Column('vessel_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('imo_number')
    )
    op.create_table('berths',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('port_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('length_m', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('max_draft_m', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('capacity_teu', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['port_id'], ['ports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('congestion_predictions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('port_id', sa.Integer(), nullable=False),
    sa.Column('prediction_time', sa.DateTime(), nullable=False),
    sa.Column('berth_utilization', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('crane_utilization', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('yard_utilization', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('arrival_pressure', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('congestion_score', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['port_id'], ['ports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cranes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('port_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('crane_type', sa.String(length=50), nullable=True),
    sa.Column('capacity_tph', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('availability_start', sa.DateTime(), nullable=True),
    sa.Column('availability_end', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['port_id'], ['ports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('simulations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('port_id', sa.Integer(), nullable=False),
    sa.Column('scenario_type', sa.String(length=50), nullable=False),
    sa.Column('scenario_parameters', sa.JSON(), nullable=True),
    sa.Column('baseline_metrics', sa.JSON(), nullable=True),
    sa.Column('simulated_metrics', sa.JSON(), nullable=True),
    sa.Column('impact_summary', sa.JSON(), nullable=True),
    sa.Column('mitigation_recommendations', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['port_id'], ['ports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('vessel_schedules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vessel_id', sa.Integer(), nullable=False),
    sa.Column('port_id', sa.Integer(), nullable=False),
    sa.Column('eta', sa.DateTime(), nullable=False),
    sa.Column('predicted_eta', sa.DateTime(), nullable=True),
    sa.Column('etd', sa.DateTime(), nullable=True),
    sa.Column('containers_teu', sa.Integer(), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['port_id'], ['ports.id'], ),
    sa.ForeignKeyConstraint(['vessel_id'], ['vessels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('old_value', sa.JSON(), nullable=True),
    sa.Column('new_value', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('optimization_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('port_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('horizon_hours', sa.Integer(), nullable=True),
    sa.Column('objective_value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['port_id'], ['ports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('berth_assignments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vessel_schedule_id', sa.Integer(), nullable=False),
    sa.Column('berth_id', sa.Integer(), nullable=False),
    sa.Column('optimization_run_id', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['berth_id'], ['berths.id'], ),
    sa.ForeignKeyConstraint(['optimization_run_id'], ['optimization_runs.id'], ),
    sa.ForeignKeyConstraint(['vessel_schedule_id'], ['vessel_schedules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crane_assignments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vessel_schedule_id', sa.Integer(), nullable=False),
    sa.Column('crane_id', sa.Integer(), nullable=False),
    sa.Column('optimization_run_id', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('productivity_teu_per_hour', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['crane_id'], ['cranes.id'], ),
    sa.ForeignKeyConstraint(['optimization_run_id'], ['optimization_runs.id'], ),
    sa.ForeignKeyConstraint(['vessel_schedule_id'], ['vessel_schedules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('operations_plans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('port_id', sa.Integer(), nullable=False),
    sa.Column('optimization_run_id', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('horizon_hours', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('summary_metrics', sa.JSON(), nullable=True),
    sa.Column('congestion_windows', sa.JSON(), nullable=True),
    sa.Column('recommendations', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['optimization_run_id'], ['optimization_runs.id'], ),
    sa.ForeignKeyConstraint(['port_id'], ['ports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recommendations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('optimization_run_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('expected_impact', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['optimization_run_id'], ['optimization_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('operation_plan_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('vessel_id', sa.Integer(), nullable=False),
    sa.Column('berth_id', sa.Integer(), nullable=True),
    sa.Column('planned_start', sa.DateTime(), nullable=False),
    sa.Column('planned_end', sa.DateTime(), nullable=False),
    sa.Column('crane_count', sa.Integer(), nullable=False),
    sa.Column('shift_label', sa.String(length=50), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['berth_id'], ['berths.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['operations_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vessel_id'], ['vessels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('operation_plan_items')
    op.drop_table('recommendations')
    op.drop_table('operations_plans')
    op.drop_table('crane_assignments')
    op.drop_table('berth_assignments')
    op.drop_table('optimization_runs')
    op.drop_table('audit_logs')
    op.drop_table('vessel_schedules')
    op.drop_table('users')
    op.drop_table('simulations')
    op.drop_table('cranes')
    op.drop_table('congestion_predictions')
    op.drop_table('berths')
    op.drop_table('vessels')
    op.drop_table('roles')
    op.drop_table('ports')
    # ### end Alembic commands ###
